export const DEFAULT_CATEGORIES = [
  { id: "cat_products", slug: "products", name: "Продукты", color: "#22c55e", icon: "🛒" },
  { id: "cat_tobacco", slug: "tobacco", name: "Табак", color: "#a16207", icon: "🚬" },
  { id: "cat_alcohol", slug: "alcohol", name: "Алкоголь", color: "#f97316", icon: "🍷" },
  { id: "cat_fastfood", slug: "fastfood", name: "Фастфуд", color: "#fb7185", icon: "🍔" },
  { id: "cat_restaurants", slug: "restaurants", name: "Кафе и рестораны", color: "#ef4444", icon: "🍽️" },
  { id: "cat_marketplaces", slug: "marketplaces", name: "Маркетплейсы", color: "#3b82f6", icon: "📦" },
  { id: "cat_digital", slug: "digital", name: "Цифровые товары", color: "#6366f1", icon: "🎮" },
  { id: "cat_subscriptions", slug: "subscriptions", name: "Подписки", color: "#06b6d4", icon: "🔁" },
  { id: "cat_telecom", slug: "telecom", name: "Связь", color: "#0ea5e9", icon: "📶" },
  { id: "cat_pharmacy", slug: "pharmacy", name: "Аптеки", color: "#84cc16", icon: "💊" },
  { id: "cat_taxi", slug: "taxi", name: "Такси", color: "#eab308", icon: "🚕" },
  { id: "cat_beauty", slug: "beauty", name: "Красота", color: "#ec4899", icon: "💄" },
  { id: "cat_pets", slug: "pets", name: "Животные", color: "#8b5cf6", icon: "🐾" },
  { id: "cat_clothes", slug: "clothes", name: "Одежда и обувь", color: "#a855f7", icon: "👕" },
  { id: "cat_utilities", slug: "utilities", name: "ЖКХ", color: "#64748b", icon: "🏠" },
  { id: "cat_person_transfers", slug: "person_transfers", name: "Переводы людям", color: "#14b8a6", icon: "👤" },
  { id: "cat_cashback", slug: "cashback", name: "Кэшбэк", color: "#10b981", icon: "💸" },
  { id: "cat_bank_fees", slug: "bank_fees", name: "Банковские комиссии", color: "#ef4444", icon: "🏦" },
  { id: "cat_other", slug: "other", name: "Прочее", color: "#94a3b8", icon: "📁" },
] as const;

export const DEFAULT_MERCHANT_RULES = [
  { id: "rule_cashback", matchType: "contains", pattern: "CASHBACK", merchantNormalized: "CashBack", categorySlug: "cashback", directionOverride: "income", priority: 950, notes: "Кэшбэк Альфы" },
  { id: "rule_alfa_smart_fee", matchType: "contains", pattern: "КОМИССИЯ ЗА АЛЬФА-СМАРТ", merchantNormalized: "Комиссия за Альфа-Смарт", categorySlug: "bank_fees", directionOverride: null, priority: 940, notes: "Комиссия банка" },
  { id: "rule_yandex_plus", matchType: "contains", pattern: "YANDEX PLUS", merchantNormalized: "Yandex Plus", categorySlug: "subscriptions", directionOverride: null, priority: 930, notes: "Подписка Yandex Plus" },
  { id: "rule_yandex_360", matchType: "contains", pattern: "YANDEX 360", merchantNormalized: "Yandex 360", categorySlug: "subscriptions", directionOverride: null, priority: 930, notes: "Подписка Yandex 360" },
  { id: "rule_yandex_lavka", matchType: "contains", pattern: "YANDEX LAVKA", merchantNormalized: "Yandex Lavka", categorySlug: "products", directionOverride: null, priority: 920, notes: "Продукты из Лавки" },
  { id: "rule_yandex_eda", matchType: "contains", pattern: "YANDEX EDA", merchantNormalized: "Yandex Eda", categorySlug: "fastfood", directionOverride: null, priority: 920, notes: "Еда/доставка" },
  { id: "rule_yandex_go", matchType: "contains", pattern: "YANDEX GO", merchantNormalized: "Yandex Go", categorySlug: "taxi", directionOverride: null, priority: 920, notes: "Такси Yandex Go" },
  { id: "rule_yandex_market", matchType: "contains", pattern: "Y M MARKET YANDEX", merchantNormalized: "Yandex Market", categorySlug: "marketplaces", directionOverride: null, priority: 920, notes: "Маркетплейс Yandex Market" },
  { id: "rule_ozon_ru", matchType: "contains", pattern: "OZON RU", merchantNormalized: "Ozon", categorySlug: "marketplaces", directionOverride: null, priority: 920, notes: "Маркетплейс Ozon" },
  { id: "rule_ozon", matchType: "contains", pattern: "OZON", merchantNormalized: "Ozon", categorySlug: "marketplaces", directionOverride: null, priority: 915, notes: "Маркетплейс Ozon" },
  { id: "rule_samokat", matchType: "contains", pattern: "SAMOKAT", merchantNormalized: "Samokat", categorySlug: "products", directionOverride: null, priority: 920, notes: "Продукты/доставка Самокат" },
  { id: "rule_pyaterochka", matchType: "contains", pattern: "PYATEROCHKA", merchantNormalized: "Пятёрочка", categorySlug: "products", directionOverride: null, priority: 910, notes: "Сеть Пятёрочка" },
  { id: "rule_lenta", matchType: "contains", pattern: "LENTA", merchantNormalized: "Лента", categorySlug: "products", directionOverride: null, priority: 910, notes: "Сеть Лента" },
  { id: "rule_magnit", matchType: "contains", pattern: "MAGNIT", merchantNormalized: "Магнит", categorySlug: "products", directionOverride: null, priority: 910, notes: "Сеть Магнит" },
  { id: "rule_vkusvill", matchType: "contains", pattern: "VKUSVILL", merchantNormalized: "ВкусВилл", categorySlug: "products", directionOverride: null, priority: 910, notes: "Магазин ВкусВилл" },
  { id: "rule_fixprice", matchType: "contains", pattern: "FIXPRICE", merchantNormalized: "Fix Price", categorySlug: "products", directionOverride: null, priority: 905, notes: "Сеть Fix Price" },
  { id: "rule_winelab", matchType: "contains", pattern: "WINELAB", merchantNormalized: "WineLab", categorySlug: "alcohol", directionOverride: null, priority: 910, notes: "Сеть WineLab" },
  { id: "rule_beeline_ru", matchType: "contains", pattern: "БИЛАЙН", merchantNormalized: "Билайн", categorySlug: "telecom", directionOverride: null, priority: 905, notes: "Связь Билайн" },
  { id: "rule_beeline_en", matchType: "contains", pattern: "VYMPELKOM", merchantNormalized: "Билайн", categorySlug: "telecom", directionOverride: null, priority: 905, notes: "Связь Билайн" },
  { id: "rule_vimpelkom_ru", matchType: "contains", pattern: "ВЫМПЕЛКОМ", merchantNormalized: "Билайн", categorySlug: "telecom", directionOverride: null, priority: 905, notes: "Связь Билайн" },
  { id: "rule_t2", matchType: "exact", pattern: "T2", merchantNormalized: "T2", categorySlug: "telecom", directionOverride: null, priority: 905, notes: "Связь T2" },
  { id: "rule_mosenergosbyt", matchType: "contains", pattern: "МОСЭНЕРГОСБЫТ", merchantNormalized: "Мосэнергосбыт", categorySlug: "utilities", directionOverride: null, priority: 905, notes: "ЖКХ" },
  { id: "rule_mosoblgaz", matchType: "contains", pattern: "МОСОБЛГАЗ", merchantNormalized: "Мособлгаз", categorySlug: "utilities", directionOverride: null, priority: 905, notes: "ЖКХ" },
  { id: "rule_mosobleirc", matchType: "contains", pattern: "МОСОБЛЕИРЦ", merchantNormalized: "Мособлеирц", categorySlug: "utilities", directionOverride: null, priority: 905, notes: "ЖКХ" },
  { id: "rule_us_polo", matchType: "contains", pattern: "U S POLO ASSN", merchantNormalized: "U.S. Polo Assn", categorySlug: "clothes", directionOverride: null, priority: 900, notes: "Одежда и обувь" },
  { id: "rule_salon_krasoty", matchType: "contains", pattern: "SALON KRASOTY", merchantNormalized: "Салон красоты", categorySlug: "beauty", directionOverride: null, priority: 900, notes: "Красота" },
  { id: "rule_zoomagazin", matchType: "contains", pattern: "ZOOMAGAZIN", merchantNormalized: "Зоомагазин", categorySlug: "pets", directionOverride: null, priority: 900, notes: "Товары для животных" },
  { id: "rule_arena_park_catering", matchType: "contains", pattern: "ARENA PARK CATERING", merchantNormalized: "Arena Park Catering", categorySlug: "fastfood", directionOverride: null, priority: 895, notes: "Фастфуд / catering" },
  { id: "rule_emoji_pizza", matchType: "contains", pattern: "ЭМЕЙЗИНГ ПИЦЦА", merchantNormalized: "Amazing Pizza", categorySlug: "fastfood", directionOverride: null, priority: 895, notes: "Пицца" },
  { id: "rule_person_transfer_out", matchType: "contains", pattern: "ИСХ. ПЕРЕВОД ПО НОМЕРУ ТЕЛЕФОНА", merchantNormalized: "Перевод по номеру телефона", categorySlug: "person_transfers", directionOverride: "expense", priority: 890, notes: "Перевод человеку" },
  { id: "rule_between_accounts", matchType: "exact", pattern: "МЕЖДУ СВОИМИ СЧЕТАМИ", merchantNormalized: "Между своими счетами", categorySlug: "other", directionOverride: null, priority: 880, notes: "Нейтральное имя для внутренних движений" },
  { id: "rule_leisure_payments", matchType: "contains", pattern: "ОПЛАТА ЗА ПОКУПКИ/ДОСУГ", merchantNormalized: "Оплата за покупки/досуг", categorySlug: "digital", directionOverride: null, priority: 870, notes: "Частый паттерн из файла" },
] as const;
